BASE_URL = "https://www.guvi.in/"
EXPECTED_TITLE = "HCL GUVI | Learn to code in your native language"
REGISTER_URL = "https://www.guvi.in/register/"
VALID_EMAIL = "vkarthik.venkatachalam@gmail.com"
VALID_PASSWORD = "Karthik#sangeeta@14"
INVALID_EMAIL = "vkarthik123@gmail.com"
INVALID_PASSWORD = "password@123"
SIGNIN_URL = "https://www.guvi.in/sign-in/?sourceUri=http%3A%2F%2Fwww.guvi.in%2F"
ERROR_MESSAGE="Incorrect Email or Password"